function S = screening_struct()
%SCREENING_STRUCT Empty engineering-workflow struct (Phase 12 interface).
%   One struct flows INPUT -> REPORT; no scattered variables.
    S = struct('image_path', '', 'image', [], ...
        'quality', struct(), 'preprocessed', [], ...
        'screening', struct(), 'anatomy', struct(), ...
        'evidence', struct(), 'explainability', struct(), ...
        'triage', struct(), 'report_path', '', 'warnings', {{}});
end
